percona/percona-everest-backend

api/backup_storage.go
api/validation.go

EVEREST-204 The old message was found confusing during the QA

EVEREST-204 Update error message

---

api-tests/tests/backup-storages.spec.ts
api-tests/tests/database-cluster-backups.spec.ts
api-tests/tests/database-cluster.spec.ts
api-tests/tests/kubernetes.spec.ts
api-tests/tests/monitoring-instances.spec.ts
api-tests/tests/psmdb-clusters.spec.ts

EVEREST-357
Fix tests broken with #141

EVEREST-357 fix tests

---

quickstart.yml

EVEREST-333
Restrict access to localhost in quickstart.yml

EVEREST-333 restrict access to localhost in quickstart

---

api-tests/tests/database-cluster.spec.ts
api/database_cluster.go
api/validation.go

EVEREST-384 Validate DatabaseCluster name

EVEREST-384 Validate DatabaseCluster name

---

api/validation.go
api/validation_test.go

EVEREST-384 [TECH DEBT] add unit-tests

EVEREST-384 [TECH DEBT] add validation unit-tests

---

.github/workflows/rc_create.yml
.github/workflows/rc_rebuild.yml

[![EVEREST-428](https://badgen.net/badge/JIRA/EVEREST-428/green)](https://jira.percona.com/browse/EVEREST-428) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
**Address the issues found during RC 0.3**
---
EVEREST-428
- failed FE build 
- wrong tag name in scripts

EVEREST-428

---

.github/workflows/build.yml

[![EVEREST-462](https://badgen.net/badge/JIRA/EVEREST-462/green)](https://jira.percona.com/browse/EVEREST-462) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
EVEREST-462
- [link]
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**

EVEREST-462 Scan dev-latest for CVEs

---

api/cluster-info.go
api/cluster-info_test.go

[![EVEREST-403](https://badgen.net/badge/JIRA/EVEREST-403/green)](https://jira.percona.com/browse/EVEREST-403) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
EVEREST-403
- [link]
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**

EVEREST-403 return the default storage class first

---

api/validation.go

[![EVEREST-301](https://badgen.net/badge/JIRA/EVEREST-301/green)](https://jira.percona.com/browse/EVEREST-301) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
EVEREST-301
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**

EVEREST-301 Clear message for failed HEAD requests to s3

---

.github/workflows/build.yml

---
**Problem:**
EVEREST-107
- [link]
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**

EVEREST-107 Migrate to trivy gh action to run cve scan

---

.github/workflows/build.yml
.github/workflows/rc_rebuild.yml
.github/workflows/release.yml

---
**Problem:**
EVEREST-107
- [link]
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**

EVEREST-107 Upgraded bit to 1.0.0 in pipelines

---

.github/workflows/rc_rebuild.yml
.github/workflows/release.yml

---
**Problem:**
EVEREST-0
- [link]
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**

EVEREST-107 Fixed build pipelines

---

deploy/quickstart-compose.yml
deploy/quickstart-k8s.yaml

---
**Problem:**
EVEREST-0
- [link]
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**

Fix main branch dev-lastest tag

---

.github/workflows/rc_rebuild.yml

---
**Problem:**
EVEREST-0
- [link]
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**

Fix RC build

---

.github/workflows/rc_rebuild.yml

- move setup-go
- change go.mod path

EVEREST-107 CI fix move setup-go, go.mod path

---

.github/workflows/build.yml

---
**Problem:**
EVEREST-107
Go version has not been configured
**CHECKLIST**
---
**Jira**
**Tests**

EVEREST-107: fix build

---

.github/workflows/release.yml
Makefile

**Release workflow fix**
---
**Problem:**
EVEREST-127
Found a couple of issues while testing if the release pipeline can build Everest.

EVEREST-107 release pipeline fix

---

deploy/quickstart-compose.yml
deploy/quickstart-k8s.yaml

**Update image ref in main**
---
**Problem:**
EVEREST-107
The Everest image in the main branch should be always `perconalab/everest:dev-latest`
⚠️ Please do not cherry pick this change to the release branch!

EVEREST-107 image ref update [main branch only]

---

.github/workflows/build.yml

---
**Problem:**
EVEREST-107
**CHECKLIST**
---
**Jira**
**Tests**

EVEREST-107: Do not use dynamic links

---

.github/workflows/build.yml
.github/workflows/rc_rebuild.yml
.github/workflows/release.yml

- Using PNPM cache
- Simpler FE build flow

chore: change FE pipelines

---

.github/workflows/ci.yml

[![EVEREST-574](https://badgen.net/badge/JIRA/EVEREST-574/green)](https://jira.percona.com/browse/EVEREST-574) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
EVEREST-574
A follow-up PR to fix CI 
- [link]
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**

EVEREST-574 Use main branch for the CLI in CI

---

.github/workflows/ci.yml
README.md

[![EVEREST-574](https://badgen.net/badge/JIRA/EVEREST-574/green)](https://jira.percona.com/browse/EVEREST-574) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
EVEREST-574
- [link]
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**

EVEREST-574 Updated README

---

Makefile

[![EVEREST-507](https://badgen.net/badge/JIRA/EVEREST-507/green)](https://jira.percona.com/browse/EVEREST-507) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
EVEREST-507
Telemetry was failed to be sent with 404, prod URL was containing slash at the end. 
**CHECKLIST**
---
**Jira**
**Tests**

EVEREST-507 Prod telemetry URL

---

.github/workflows/rc_create.yml
.github/workflows/release.yml

---
**Problem:**
EVEREST-0
- [link]
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**

EVEREST-107 Remove quickstart-compose

---

api-tests/tests/backup-storages.spec.ts
api/backup_storage.go
api/validation.go

[![EVEREST-539](https://badgen.net/badge/JIRA/EVEREST-539/green)](https://jira.percona.com/browse/EVEREST-539) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
EVEREST-539
- [link]
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**

EVEREST-539 Fixed panic on update backup storage

---

api-tests/tests/auth.spec.ts
api/everest.go
pkg/auth/token.go

[![EVEREST-692](https://badgen.net/badge/JIRA/EVEREST-692/green)](https://jira.percona.com/browse/EVEREST-692) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
**Rename password to token**
---
**Problem:**
EVEREST-692
Calling it password is incorrect as passwords are usually used in conjunction with a user name. This is a authorization token, let's call it that.
**Solution:**
Rename password command to token
**CHECKLIST**
---
**Jira**
**Tests**

EVEREST-692 Rename password to token

---

.github/workflows/ci.yml

[![EVEREST-704](https://badgen.net/badge/JIRA/EVEREST-704/green)](https://jira.percona.com/browse/EVEREST-704) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
EVEREST-0
- [link]
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[EVEREST-704]: https://perconadev.atlassian.net/browse/EVEREST-704?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYz …

EVEREST-704 Fixed pipeline

---

api/database_cluster_restore.go

[![EVEREST-664](https://badgen.net/badge/JIRA/EVEREST-664/green)](https://jira.percona.com/browse/EVEREST-664) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
**Improve error message**
---
**Problem:**
EVEREST-664
**CHECKLIST**
---
**Jira**
**Tests**
- ~[ ] Is an Integration test/test case added for the new feature/change?~
- ~[ ] Are unit tests added where appropriate?~
[EVEREST-664]: https://perconadev.atlassian.net/browse/EVEREST-664?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

EVEREST-664 Improve error message

---

.github/workflows/rc_create.yml

---
**Problem:**
EVEREST-0
- [link]
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[EVEREST-107]: https://perconadev.atlassian.net/browse/EVEREST-107?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYz …

EVEREST-107 update rc creation

---

.github/workflows/ci.yml
README.md
api-tests/README.md
api/everest_test.go
go.mod
go.sum
pkg/auth/token.go
pkg/kubernetes/monitoring_config.go

[![EVEREST-633](https://badgen.net/badge/JIRA/EVEREST-633/green)](https://jira.percona.com/browse/EVEREST-633) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
**Rename restricted namespaces**
---
**Problem:**
EVEREST-633
`everest-system` and `everest-monitoring` are more descriptive names that `percona-everest` and `percona-everest-monitoring`.
**CHECKLIST**
---
**Jira**
**Tests**
[EVEREST-633]: https://perconadev.atlassian.net/browse/EVEREST-633?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

EVEREST-633 Rename restricted namespaces

---

.github/workflows/ci.yml
api-tests/tests/backup-storages.spec.ts
api-tests/tests/database-cluster.spec.ts
api-tests/tests/helpers.ts
api-tests/tests/monitoring-instances.spec.ts
api/backup_storage.go
api/everest-server.gen.go
api/monitoring_instance.go
api/validation.go
client/everest-client.gen.go
docs/spec/openapi.yml
go.mod
go.sum

TargetNamespaces wasn't very clear so we renamed it to AllowedNamespaces.
[EVEREST-107]: https://perconadev.atlassian.net/browse/EVEREST-107?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

EVEREST-107 Rename TargetNamespaces to AllowedNamespaces
