README.md
EVEREST-294
Suggest using docker compose v2 to avoid compatibility issues.
=> EVEREST-294 Suggest using docker compose v2

api/database_cluster.go
EVEREST-321
Right now it's the easiest solution to make the version immutable. However, the validation will be improved in EVEREST-256
=> EVEREST-321 Disable editing engine version

model/backup_storage.go
EVEREST-330
We were creating the k8s secret with the everest internal secret IDs as the keys while it expects `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`.
=> EVEREST-330 Fix backup storage secret format

api/validation.go
EVEREST-357
Prevent resource names exceeding RFC1123 size limits by limiting the cluster name to 22 characters.
=> EVEREST-357 reduce cluster name size limit to 22

api-tests/tests/backup-storages.spec.ts, api/database_cluster_backup.go, api/database_cluster_restore.go, api/validation.go, api/validation_test.go
[![EVEREST-271](https://badgen.net/badge/JIRA/EVEREST-271/green)](https://jira.percona.com/browse/EVEREST-271) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
**Update error messages**
---
**Problem:**
EVEREST-271
Outdated error message/function names that refers to RFC-1123
**Cause:**
PXC imposes to follow RFC-1035 + the rule of maximum length 22. 
**Solution:**
Update the error message and the naming in the codebase
**CHECKLIST**
---
**Jira**
**Tests**
=> EVEREST-271 RFC-1035 error messages

.github/workflows/build.yml
**Locked bvm version**
---
To avoid problems with the bit versions, the FE pipeline currently locks the bvm version, let's use the same approach for the dev-latest builds. 
It works, tested it here https://github.com/percona/percona-everest-backend/pull/157
=> EVEREST-107 fix dev-latest: locked bvm version

api-tests/tests/database-cluster.spec.ts, api/backup_storage.go, api/database_cluster.go, api/database_cluster_backup.go, api/database_cluster_restore.go, api/everest.go, api/kubernetes.go, api/monitoring_instance.go, pkg/configs/configs.go, pkg/kubernetes/client/client.go
[![EVEREST-435](https://badgen.net/badge/JIRA/EVEREST-435/green)](https://jira.percona.com/browse/EVEREST-435) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
EVEREST-435
The backend runs a lot of goroutines without cancellation/synchronization and it's unclear when they exit
- [link]
**Cause:**
**Solution:**
Since Everest supports only one kubernetes installation it does not make any sense to perform operations against …
=> EVEREST-435 Ensure Backend does not run uncontrollable goroutines

deploy/quickstart-compose.yml
[![EVEREST-444](https://badgen.net/badge/JIRA/EVEREST-444/green)](https://jira.percona.com/browse/EVEREST-444) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
**Problem:**
In [EVEREST-333](https://jira.percona.com/browse/EVEREST-333) (#142) we identified and fixed a security vulnerability where we were exposing everest's port to 0.0.0.0 by default.
However, this fix broke the ability for users to access everest from outside localhost which is must have.
- #142
**Cause:**
#142 
**Solution:**
Add a `EVEREST_BIND_ADDR` env var which is `127.0.0.1` by default but …
=> EVEREST-444 Add configurable bind address for the everest container

.golangci.yml, api/database_cluster.go, api/validation.go, api/validation_test.go, pkg/kubernetes/client/customresources/databaseclusters.go, pkg/kubernetes/client/customresources/databaseengines.go, pkg/kubernetes/client/database_engine.go, pkg/kubernetes/client/kubeclient_interface.go, pkg/kubernetes/client/mock_kube_client_connector.go, pkg/kubernetes/database_engine.go
[![EVEREST-256](https://badgen.net/badge/JIRA/EVEREST-256/green)](https://jira.percona.com/browse/EVEREST-256) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
EVEREST-256 Requires validation improvements for a database cluster CR before proxying and storing in etcd.
- https://github.com/percona/everest-operator/pull/50
**Cause:**
**Solution:**
I had …
=> EVEREST-256 Improved validation of database cluster CR

.github/workflows/rc.yml, .github/workflows/rc_create.yml, .github/workflows/rc_rebuild.yml
[![EVEREST-428](https://badgen.net/badge/JIRA/EVEREST-428/green)](https://jira.percona.com/browse/EVEREST-428) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
**RC pipleline**
---
**Problem:**
EVEREST-428
Everest needs a workflow for building release branches.
**Solution:**
Create a manually triggering workflow. It would accept the version we want to create the RC for and would create the `release-*.*.*` branches in the backend, cli, frontend and catalog repos. It will update tags in the deployment scripts (so no manual intervention needed to run it from the rc-branch), build and push …
=> EVEREST-428-rc-pipeline

.github/workflows/rc_rebuild.yml
[![EVEREST-428](https://badgen.net/badge/JIRA/EVEREST-428/green)](https://jira.percona.com/browse/EVEREST-428) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
**UPDATE RC CI**
---
**Problem:**
EVEREST-428
*The `rc_rebuild` workflow wasn't triggered after the  `rc_create` even though there was a push to the existing release branch. However the manual commit to that branch triggers the workflow just fine*
**Cause:**
*Workflows can not trigger other workflows by design to prevent endless loops*
**Solution:**
*Configure the workflow run explicitly*
**CHECKLIST**
---
**Jira**
**Tests**
=> EVEREST-428

api/database_cluster.go, api/validation.go
[![EVEREST-468](https://badgen.net/badge/JIRA/EVEREST-468/green)](https://jira.percona.com/browse/EVEREST-468) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
EVEREST-468
We can scale down multiple node clusters to a single node but we need to set `allowUnsafeConfigurations` to `true`. Having this configuration is not recommended and makes a database cluster unsafe. Once allowUnsafeConfigurations set to true you can't set it to false for all operators and psmdb operator does not support it. Once it is supported …
=> EVEREST-468 Restrict scaling down to single node cluster

.github/workflows/release.yml, Dockerfile, Makefile, cmd/config/config.go
[![EVEREST-506](https://badgen.net/badge/JIRA/EVEREST-506/green)](https://jira.percona.com/browse/EVEREST-506) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
**Distinguish release builds**
---
**Problem:**
EVEREST-506
With the current TelemetryURL configuration the test/dev data can still appear in prod telemetry (when testing dev-latest or rc builds). 
**Solution:**
Do not set the prod TelemetryURL as default. 
Set the url to the prod value _only_ when building a release image, so by default no url is set at all. 
For the testing purposes use the …
=> EVEREST-506 Prod telemetry

.github/workflows/build.yml, .github/workflows/rc_rebuild.yml, .github/workflows/release.yml
---
**Problem:**
EVEREST-0
- [link]
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
=> EVEREST-107 Fixing the pipeline

api/deps.go, api/everest.go, api/telemetry.go, cmd/config/config.go, cmd/main.go, migrations/000008_create_settings_table.down.sql, migrations/000008_create_settings_table.up.sql, model/settings.go
[![EVEREST-507](https://badgen.net/badge/JIRA/EVEREST-507/green)](https://jira.percona.com/browse/EVEREST-507) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
**Collect and report metrics**
---
**Problem:**
EVEREST-507
Report the db engines metrics - how many db clusters of each type are running. 
A step forward multi k8s support - generate own Everest ID instead of using the k8s cluster ID. 
The telemetry request [example](https://www.notion.so/percona/Pillars-Telemetry-Design-efea81c1f170456099503bbcdbd0ad9b?pvs=4#fb2130ee3a30425c9e3dd45045f34235) 
**CHECKLIST**
---
**Jira**
**Tests**
=> EVEREST-507 Report metrics

.github/workflows/rc_rebuild.yml
---
**Problem:**
EVEREST-107
Disable cgo so we don't use dynamic links.
**Cause:**
`libc` is not available in `scratch` image
**CHECKLIST**
---
**Jira**
**Tests**
=> EVEREST-107: Disable cgo

.github/workflows/rc_rebuild.yml
---
**Problem:**
EVEREST-107
It's not clear what assets are copied from FE.
**Solution:**
Make `cp` verbose when copying assets.
**CHECKLIST**
---
**Jira**
**Tests**
=> EVEREST-107: more verbose rc build

deploy/quickstart-k8s.yaml
---
**Problem:**
EVEREST-107
The current deployment to k8s uses the LoadBalancer as the default service type which exposes everest to outside the cluster.
**Solution:**
Use ClusterIP as the default service type and add documentation on how to change it.
=> EVEREST-107 use ClusterIP as default service type

.github/workflows/build.yml
[![EVEREST-559](https://badgen.net/badge/JIRA/EVEREST-559/green)](https://jira.percona.com/browse/EVEREST-559) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
**EVEREST-559 fix version fetched by build pipeline**
---
**Problem:**
EVEREST-559
The everest version is incorrect.
**Cause:**
With the default configuration, the github actions/checkout@v4 only fetches the main branch. Without tag information git describe isn't able to get the correct version.
**Solution:**
Since we need to call git describe to get the everest version we also need to fetch the tags. Therefore, we need to set …
=> EVEREST-559 fix version fetched by build pipeline

api/database_cluster.go, pkg/kubernetes/database_cluster_backup.go
[![EVEREST-737](https://badgen.net/badge/JIRA/EVEREST-737/green)](https://jira.percona.com/browse/EVEREST-737) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
**Fix wrong base backup with PITR**
---
**Problem:**
EVEREST-737
The PITR was taking the wrong backup as a base for PITR.
**Cause:**
When searching for the latest backup we were getting all backups without any filtering.
**Solution:**
When getting the list of backups we need to filter just for the backups of the given DBC, we can use the clusterName label for that.
**CHECKLIST**
---
**Jira**
**Tests**
- ~[ ] Is an Integration …
=> EVEREST-737 fix wrong base backup with PITR

api/validation.go, go.mod, go.sum
[![EVEREST-539](https://badgen.net/badge/JIRA/EVEREST-539/green)](https://jira.percona.com/browse/EVEREST-539) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
**EVEREST-539: fix PATCH BackupStorages**
---
**Problem:**
EVEREST-539
Editing a backup storage always returns an error saying that the credentials are invalid
**Cause:**
We were trying to decode a plain-text string as if it was encoded in base64.
**Solution:**
Don't decode the secret, client-go already takes care of decoding it to plain-text.
**CHECKLIST**
---
**Jira**
**Tests**
[EVEREST-539]: …
=> EVEREST-539: fix PATCH BackupStorages

pkg/kubernetes/monitoring_config.go
[![EVEREST-734](https://badgen.net/badge/JIRA/EVEREST-734/green)](https://jira.percona.com/browse/EVEREST-734) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
EVEREST-734
When monitoring was not enabled and VM Agent CRD was not present, a monitoring config cannot be removed.
**Solution:**
Handle missing CRD error.
**CHECKLIST**
---
**Jira**
**Tests**
=> EVEREST-734: do not fail on vmagent not present

api/database_cluster.go
[![EVEREST-781](https://badgen.net/badge/JIRA/EVEREST-781/green)](https://jira.percona.com/browse/EVEREST-781) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
**Use databaseAdmin user in MongoDB clusters**
---
**Problem:**
EVEREST-781
User is unauthorized for managing DBs.
**Cause:**
The `userAdmin` doesn't have permissions to manage DBs
**Solution:**
Use `databaseAdmin` user.
**CHECKLIST**
---
**Jira**
**Tests**
- ~[ ] Is an Integration test/test case added for the new feature/change?~
- ~[ ] Are unit tests added where appropriate?~
[EVEREST-781]: …
=> EVEREST-781 Use databaseAdmin user in MongoDB clusters

api/validation.go, api/validation_test.go, go.mod, go.sum
[![EVEREST-638](https://badgen.net/badge/JIRA/EVEREST-638/green)](https://jira.percona.com/browse/EVEREST-638) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
EVEREST-638
Added validation for DataSource in `DatabaseCluster` and `DatabaseClusterRestore`
- https://github.com/percona/everest-operator/pull/258
**CHECKLIST**
---
**Jira**
**Tests**
~~- [ ] Is an Integration test/test case added for the new feature/change?~~
[EVEREST-638]: https://perconadev.atlassian.net/browse/EVEREST-638?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3M …
=> EVEREST-638 DataSource validation

api/validation.go, go.mod, go.sum
[![EVEREST-539](https://badgen.net/badge/JIRA/EVEREST-539/green)](https://jira.percona.com/browse/EVEREST-539) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
**Fix editing of backup storage**
---
**Problem:**
EVEREST-539
Users are unable to update a backup storage if they try to change the region or endpointURL.
**Cause:**
We weren't getting the region and endpointURL from the request.
**Solution:**
Get both of those values from the request
**CHECKLIST**
---
**Jira**
**Tests**
- ~[ ] Is an Integration test/test case added for the new feature/change?~
- ~[ ] Are unit tests added where …
=> EVEREST-539 Fix editing of backup storage

api/backup_storage.go, api/database_cluster.go, api/everest-server.gen.go, api/kubernetes.go, api/monitoring_instance.go, api/validation.go, client/everest-client.gen.go, deploy/quickstart-k8s.yaml, docs/spec/openapi.yml, pkg/auth/token.go, pkg/kubernetes/client/kubeclient_interface.go, pkg/kubernetes/client/mock_kube_client_connector.go, pkg/kubernetes/client/monitoring_config.go, pkg/kubernetes/client/secret.go, pkg/kubernetes/monitoring_config.go, pkg/kubernetes/secret.go
[![EVEREST-496](https://badgen.net/badge/JIRA/EVEREST-496/green)](https://jira.percona.com/browse/EVEREST-496) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
**Add multi namespaces monitoring**
---
**NOTE FOR REVIEWERS: Still missing api-tests,  I'll submit a follow-up PR to address the integration tests once the dependencies are sorted out.**
**Problem:**
EVEREST-496
- https://github.com/percona/everest-operator/pull/265
With the changes introduced in https://github.com/percona/everest-operator/pull/265 we no longer need the /cluster-monitoring endpoint so it …
=> EVEREST-496 Add multi namespaces monitoring

.github/workflows/ci.yml, api-tests/tests/auth.spec.ts, api-tests/tests/backup-storages.spec.ts, api-tests/tests/database-cluster-backups.spec.ts, api-tests/tests/database-cluster-restores.spec.ts, api-tests/tests/database-cluster.spec.ts, api-tests/tests/database-engines.spec.ts, api-tests/tests/helpers.ts, api-tests/tests/kubernetes.spec.ts, api-tests/tests/monitoring-instances.spec.ts, api-tests/tests/pg-clusters.spec.ts, api-tests/tests/psmdb-clusters.spec.ts, api-tests/tests/pxc-clusters.spec.ts, api-tests/tests/version.spec.ts, api/everest_test.go, api/monitoring_instance.go
**Update CI**
---
**Problem:**
EVEREST-107
- Update tests to use multinamespace. 
- Remove `monitroring enable`
- Log details of failures
[EVEREST-107]: https://perconadev.atlassian.net/browse/EVEREST-107?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> EVEREST-107 update api-tests for multinamespace

api/database_cluster_backup.go, api/validation.go, api/validation_test.go
[![EVEREST-832](https://badgen.net/badge/JIRA/EVEREST-832/green)](https://jira.percona.com/browse/EVEREST-832) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
**Fix access to namespaces**
---
**Problem:**
EVEREST-832
DBCs and DBBs had access to all BackupStorages and MonitoringConfigs regardless of the namespace.
**Cause:**
We weren't validating if a given BackupStorage or MonitoringConfig was allowed in the DBC's namespace.
**Solution:**
Validate if a given BackupStorage or MonitoringConfig is allowed in the DBC's namespace.
**CHECKLIST**
---
**Jira**
**Tests**
[EVEREST-832]: …
=> EVEREST-832 Fix access to namespaces

.github/workflows/ci.yml, api-tests/tests/backup-storages.spec.ts, api-tests/tests/database-cluster.spec.ts, api-tests/tests/helpers.ts, api-tests/tests/monitoring-instances.spec.ts, api/backup_storage.go, api/everest-server.gen.go, api/monitoring_instance.go, api/validation.go, client/everest-client.gen.go, docs/spec/openapi.yml, go.mod, go.sum
Reverts percona/percona-everest-backend#456
=> Revert "EVEREST-107 Rename TargetNamespaces to AllowedNamespaces"

.github/workflows/ci.yml, api-tests/tests/backup-storages.spec.ts, api-tests/tests/database-cluster.spec.ts, api-tests/tests/helpers.ts, api-tests/tests/monitoring-instances.spec.ts, api/backup_storage.go, api/everest-server.gen.go, api/monitoring_instance.go, api/validation.go, client/everest-client.gen.go, docs/spec/openapi.yml, go.mod, go.sum
TargetNamespaces wasn't very clear so we renamed it to AllowedNamespaces.
After fixing the perconalab/everest-catalog:latest image I'm re-opening the #456 without any changes.
[EVEREST-107]: https://perconadev.atlassian.net/browse/EVEREST-107?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> EVEREST-107 Rename TargetNamespaces to AllowedNamespaces
